### ISSUE TITLE
Renderflex overflowed by 5.0 pixels on the bottom of YearsView

### ISSUE THREAD

**Issue by Ahmadre** [mennorenkens/flutter_scrolling_calendar#4]
**Problem:**
- When you download the latest version ^1.2.0, the bottom of all of the last years overflowed by 5.0 pixels. 

**Solution:**
I changed the value in `getYearViewHeight()` by:

```dart
    const double topPadding = 17.0;
```

and Added zero Padding on the YearViews. That worked for me. Maybe there's a cleaner solution for all these overflowes.

By the way: I Added a lot of parameters like:

```dart
    yearTitleColor: Colors.white,
    monthTitleColor: Colors.white,
    monthDaysColor: Colors.white,
    dividerColor: Colors.white30,
```

which were missing.

Best regards
Rebar

PS: thank you so much for this package!

**Comment by mennorenkens** [comment]
Hey @Ahmadre ! I checked this and I'm afraid it is not fixed by simply changing the topPadding value. The amount of overflow seems to be dependent on phone dimensions. Currently I do not have the time to look into this, but luckily you could fix this yourself for your case 👍. Feel free to make a pull request if you have a fix :)
